working with new cmake

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -69,10 +69,16 @@ script:
   - travis_wait 100 R CMD build ${PROJ_DIR} ${R_BUILD_ARGS}
   - rm -f travis_wait*.log
   - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)  
-  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}";
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}";  CHECK_RET=$? ;
   - rm -f travis_wait*.log
-  - check_fail
-  - check_warnings
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed"; 
+      check_fail; 
+      dump_logs; 
+      check_warnings ;      
+      travis_terminate 1;
+    fi 
 
 jobs:
   include:
